void rly(void);
void can(void);
void com(void);
void tmr(void);
void canr(void);
void cant(void);
void gpsr(void);
void acsr(void);
void acst(void);
void fcs(void);
void mls(void);
void ets(void);
void dgps(void);
void dacs(void);
void cani(void);
void tmri(void);
void mlsp(unsigned char avail, MLSD *mlsd, unsigned char *force);
