struct ll {
	unsigned char key;
	struct ll *next;
};

struct ll *llcreate(void);
struct ll *lltail(struct ll *p);
struct ll *llmax(struct ll *p);
struct ll *llmin(struct ll *p);
struct ll *llfind(struct ll *p, unsigned char key);
struct ll *llget(struct ll *p, unsigned char key);
struct ll *llstrip(struct ll *p, struct ll *node);
struct ll *llbehead(struct ll *p);
unsigned lllen(struct ll *p);
unsigned llscan(struct ll *p, unsigned char key);
unsigned lldelscan(struct ll *p, unsigned char key);
unsigned llrep(struct ll *p, unsigned char key, unsigned char new);
void llins(struct ll *p, unsigned char key);
void llinstail(struct ll *p, unsigned char key);
void lladd(struct ll *p, struct ll *node);
void lladdtail(struct ll *p, struct ll *node);
void lldel(struct ll *p);
void lldeltail(struct ll *p);
void lldelfind(struct ll *p, unsigned char key);
void llbuild(struct ll *p, unsigned n, unsigned char key);
void llinit(struct ll *p, unsigned n, unsigned char *buf);
void llcpy(unsigned char *buf, unsigned n, struct ll *p);
void llclean(struct ll *p);
void lldestroy(struct ll *p);
void llrev(struct ll *p); 
void llwrap(struct ll *p);
